version: "3"
networks: 
    flasky-network:
        external: true
services:
    nginx:
        image: nginx:1.17.10
        volumes: 
            - "./conf.d/default.conf:/etc/nginx/conf.d/default.conf"
        ports: 
            - 80:80
        networks: 
            - flasky-network
        depends_on: 
            - flasky
    flasky:
        build: .
        volumes: 
            - "./:/usr/src/app"
        ports: 
            - 3000:3000
        networks: 
            - flasky-network