version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7
        name: flasky
      - image: circleci/nginx:1.17.10
        name: nginx
    steps:
    - checkout
    - run: docker run flasky
    - run: docker run flasky