version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3
    machine: true
    steps:
      - checkout
      # - run: sudo apt-get install docker -y
      # - run: sudo curl -L "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      # - run: sudo chmod +x /usr/local/bin/docker-compose
      - run: docker network create flasky-network
      - run: docker-compose up -d
      - run: pip3 install --upgrade pip3 && pip install -r requirements.txt
      - run: python3 manage.py
      - run: docker-compose down