version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout:
      - run:
        name: Installing the deps
        command: python -m pip install ./requirements.txt
      - run:
        name: Testing
        command: python manage.py