version: 2.1

jobs:
  build:
    steps:
    - checkout
    - run: apt-get in
    - run: docker build -t flasky-app .
    # - run: docker run flasky
    docker:
      - image: flasky-app
    steps:
      - checkout
      - run: docker-compose up
      - run: python manage.py