version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: ls -al requirements.txt
      - run: pip install -r requirements.txt
      # - run: python manage.py