version: 2.1

jobs:
  build:
    working_directory: ~/
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: python -m pip install ./requirements.txt
      - run: python manage.py