version: 2.1

jobs:
  build:
    machine: true
    steps:
      - checkout
      # - run: sudo apt-get install docker -y
      # - run: sudo curl -L "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      # - run: sudo chmod +x /usr/local/bin/docker-compose
      - run: docker network create flasky-network
      - run: docker-compose up
      - run: python manage.py
      - run: docker-compose down