version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: apt-get install docker-engine -y
      - run: service docker start 
      - run: curl -L "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      - run: chmod +x /usr/local/bin/docker-compose
      - run: docker network create flasky-network
      - run: docker-compose up
      - run: python manage.py
      - run: docker-compose down