version: 2.1

jobs:
  build:
    steps:
      - checkout
      - run: docker network create flasky-network
      - run: docker-compose up
      - run: python manage.py
      - run: docker-compose down