version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: docker network create flasky-network
      - run: docker-compose up
      - run: python manage.py
      - run: docker-compose down